Models/Dish.cs
namespace Menu.Models
{
    public class Dish
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public double Price { get; set; }
        public List<DishIngredient>? DishIngredients { get; set; }
    }
}

Models/DishIngredient.cs
namespace Menu.Models
{
    public class DishIngredient
    {
        public int DishId { get; set; }
        public Dish Dish { get; set; }
        public int IngredientId { get; set; }
        public Ingredient Ingredient { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace Menu.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Ingredient.cs
namespace Menu.Models
{
    public class Ingredient
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<DishIngredient>? DishIngredients { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Menu.Models;

namespace Menu.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using Menu.Data;
using Menu.Models;
using Microsoft.EntityFrameworkCore;

namespace Menu.Controllers
{

    public class MenuController : Controller
    {
        private readonly MenuContext _context;
        public MenuController(MenuContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(string searchString)
        {
            var dishes = from d in _context.Dishes
                       select d;
            if (!String.IsNullOrEmpty(searchString))
            {
                dishes = dishes.Where(d => d.Name.Contains(searchString));
            }
            return View(await dishes.ToListAsync());
        }
        public async Task<IActionResult> Details(int? id)
        {
            var dish = await _context.Dishes
            .Include(di => di.DishIngredients)
            .ThenInclude(i => i.Ingredient)
            .FirstOrDefaultAsync(x => x.Id == id);
            if (dish == null)
            {
                return NotFound();
            }
            return View(dish);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Menu/Details.cshtml
@model Menu.Models.Dish
@{
    ViewData["Title"] = " Details";
}

<div class="container">
    <div class="d-flex justfiy-content-center">
        <h2>Model.Name</h2>
    </div>
        <div class="d-flex justify-content-center">

            <img src="@Model.ImageUrl" width="50%" />

        </div>
            
        <div class="d-flex justify-content-center">

             @Model.Price.ToString("N2") Dollars

         </div>
         <div class="d-flex justify-content-center">
            Ingredinets:
            <ui>
                @foreach (var item in Model.DishIngredients)
                {
                    <li>
                    
                    @item.Ingredient.Name

                    </li>
                }
            </ul>
         </div>
         <a class="btn btn-primary" asp-action="Index">Back to The Menu</a>
</div>

Views/Menu/index.cshtml
@model List<Menu.Models.Dish>
@{
    ViewData["Title"] = "MenuIndex";
}

<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-6">
                <div class="d-flex justify-content-center">
                    @item.Name
                </div>
                <div class="d-flex justify-content-center">
                    <img src="@item.ImageUrl" width="70%" />
                </div>
                <div class="d-flex justify-content-center">
                    @item.Price.ToString("N2") Dollars
                </div>
                <div class="d-flex justify-content-center">
                    <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id"> View Dish</a>
                </div>
            </div>
        }
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Menu</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Menu.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css" integrity="sha512-DxV+EoADOkOygM4IR9yXP8Sb2qwgidEmeqAEmDKIOfPRQZOWbXCzLC6vjbZyy0vPisbH2SyW27+ddLVCN+OMzQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Menu" asp-action="Index">Menu</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" style="margin:auto">
                             <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="Index">Menu</a>
                        </li>
                        <form asp-controller="Menu" asp-action="Index" method="get">
                            <input style="width: 80%; float: left border-radius-top-left-radius: 20px; border-bottom-left-radius: 20px; background:transparent" type="text" name="searchString" class="form-control" />
                            <button style="width: 20%; float: left-top; border:none; background:transparent; height: 40px" type="submit" ><i class="fa fa-search"></i></button>
                        </form>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Menu - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>